# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets, Qt

# class PatientCombo(object):
#     def __init__(self):
#         super().__init__()

def setupComboUi(SelectPatientWidget):
    ComboName = QtWidgets.QComboBox(SelectPatientWidget)
    ComboName.setGeometry(QtCore.QRect(20, 20, 361, 41))
    font = QtGui.QFont()
    font.setPointSize(23)
    font.setItalic(True)
    ComboName.setFont(font)
    ComboName.setObjectName("ComboName")
    ComboName.addItem("")
    ComboNumber = QtWidgets.QComboBox(SelectPatientWidget)
    ComboNumber.setGeometry(QtCore.QRect(400, 20, 141, 41))
    font = QtGui.QFont()
    font.setPointSize(23)
    font.setItalic(True)
    ComboNumber.setFont(font)
    ComboNumber.setObjectName("ComboNumber")
    ComboNumber.addItem("")
    ComboEar = QtWidgets.QComboBox(SelectPatientWidget)
    ComboEar.setGeometry(QtCore.QRect(550, 20, 71, 41))
    font = QtGui.QFont()
    font.setPointSize(24)
    font.setItalic(True)
    ComboEar.setFont(font)
    ComboEar.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
    ComboEar.setFocusPolicy(QtCore.Qt.WheelFocus)
    ComboEar.setObjectName("ComboEar")
    ComboEar.addItem("")
    ComboEar.addItem("")
    ComboLevel = QtWidgets.QComboBox(SelectPatientWidget)
    ComboLevel.setGeometry(QtCore.QRect(630, 20, 91, 41))
    font = QtGui.QFont()
    font.setPointSize(23)
    font.setItalic(True)
    ComboLevel.setFont(font)
    ComboLevel.setObjectName("ComboLevel")
    ComboLevel.addItem("")
    ComboStim = QtWidgets.QComboBox(SelectPatientWidget)
    ComboStim.setGeometry(QtCore.QRect(730, 20, 161, 41))
    font = QtGui.QFont()
    font.setPointSize(23)
    font.setItalic(True)
    ComboStim.setFont(font)
    ComboStim.setObjectName("ComboStim")
    ComboStim.addItem("")
    return ComboName, ComboNumber, ComboEar, ComboLevel, ComboStim

def populate_combos():
    for idx in range(len(self.name)):ComboName.addItem("")
    for idx in range(5):ComboNumber.addItem("")
    for idx in range(2):ComboEar.addItem("")
    for idx in range(5):ComboLevel.addItem("")
    for idx in range(10):ComboStim.addItem("")
